# Generated by Django 4.0.1 on 2022-01-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kbid', models.CharField(max_length=15)),
                ('cveid', models.CharField(max_length=50)),
                ('exp', models.CharField(max_length=100)),
            ],
        ),
    ]
