# Generated by Django 4.0.1 on 2022-01-23 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KB',
            new_name='KBinfo',
        ),
    ]
