# Generated by Django 4.0.1 on 2022-01-23 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_rename_kb_kbinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KBinfo',
            new_name='KB',
        ),
    ]
